spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=secondr
spring.data.mongodb.auto-index-creation=true

spring.application.name=booking

jwt.secret=hfaiehfisehfosndfejndfeswljrfeowfnjehwbewios4ngvhtrwglp4rkledf
jwt.expirationMs=36000000
# App properties